### ISSUE TITLE
S3 session initialization without static creds

### ISSUE THREAD

**Issue by sosedoff** [dfuse-io/dstore#3]
Currently the S3 session is initialized via `session.NewSession(awsConfig)` which expects static credentials by default and does not seem to support standard AWS_* env vars.

I can submit a PR that will use `session.NewSession` without args and let AWS figure out how to do auth if provided storage url does not contain key/secret pairs. I have it working in a local fork, but wanted to see if you're interested in this kind of a change.

**Comment by maoueh** [comment]
Yeah we will accept such change, go ahead and I'll review.
